[package]
name = "ethbot"
version = "0.1.0"
authors = ["NikVolf <nikvolf@gmail.com>"]

[dependencies]
ethbot-core = { path = "core" }
ethbot-runner = { path = "runner" }

[workspace]
members = [
    "./",
    "runner",
    "core"
]